### ISSUE TITLE
Hello world Dapper

### ISSUE THREAD

**Issue by DiscoDancer** [DiscoDancer/FunWithWpf#4]
- clone this repository ('git clone https://github.com/DiscoDancer/FunWithWpf')
- create project console application (.NET Framework)
- add dapper (use Nuget)
- add connection string
- get data from customers table

**Comment by DiscoDancer** [comment]
https://www.codeproject.com/Articles/212274/A-Look-at-Dapper-NET

**Comment by DiscoDancer** [comment]
https://www.youtube.com/watch?v=JfpCicDUMKc

**Comment by DiscoDancer** [comment]
https://www.youtube.com/watch?v=v7GbxUnwRY8

**Comment by DiscoDancer** [comment]
те видео могут быть хуевыми ! можно поискать что-то другое

**Comment by DusciCat** [comment]
Ок


3 дек. 2017 г. 9:26 PM пользователь "Disco Dancer" <notifications@github.com>
написал:
