### ISSUE TITLE
Обновить схему

### ISSUE THREAD

**Issue by DiscoDancer** [DiscoDancer/FunWithWpf#40]
- Нужно добавить таблицу ProductCategory с полем ProductCategoryID(INT PK Autogen) и Name (VARCHAR 100 NOT NULL).
- Соовественно обновить скрипты для создания таблиц и заполнения данными
- У всех продуктов (в начальных данных) должна быть проставлена категогрия
- Для продукта CategoryID FK NOT NULL

**Comment by DusciCat** [comment]
https://gist.github.com/DusciCat/25d8f1ef3f06688ebb0b8d187b058c94
https://gist.github.com/DusciCat/1e3fd5b0c5688c4c9e016ffb4ab5b82f
